#PBS -N compression_mpi
#PBS -q fthpc -l select=1:ncpus=32:mpiprocs=32:mem=372gb:interconnect=25ge,walltime=64:30:00

source /home/dkrasow/spack/share/spack/setup-env.sh

#spack load py-h5py
#spack load py-matplotlib  
#spack load qcat
#spack load libpressio  
#spack load libpressio-tthresh 
#spack load r

cd compression
#load env
spack env activate . 

#mpiexec -n 32 python -m mpi4py single_stat_script.py
#mpiexec -n 32 python -m mpi4py process_script_mpi.py
python import_script.py

