rm(list=ls())

install.packages('microbenchmark', repos = "http://cran.us.r-project.org")
install.packages('mgcv', repos = "http://cran.us.r-project.org")
install.packages('glmnet', repos = "http://cran.us.r-project.org")
install.packages('dplyr', repos = "http://cran.us.r-project.org")
install.packages('fields', repos = "http://cran.us.r-project.org")
install.packages('pals', repos = "http://cran.us.r-project.org")
install.packages('viridis', repos = "http://cran.us.r-project.org")
install.packages('png', repos = "http://cran.us.r-project.org")
install.packages('rhdf5', repos = "http://cran.us.r-project.org")